# Generated by Django 5.1.3 on 2025-05-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='car',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='parkinglog',
            name='is_reservation',
            field=models.BooleanField(default=False, verbose_name='Резервация'),
        ),
        migrations.AddField(
            model_name='parkinglog',
            name='reservation_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец резервации'),
        ),
        migrations.AddField(
            model_name='parkinglog',
            name='reservation_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало резервации'),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='reservation_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец резервации'),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='reservation_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало резервации'),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='reservation_timeout',
            field=models.IntegerField(default=15, verbose_name='Таймаут резервации в минутах'),
        ),
    ]
